In [1]:
import numpy as np

In [8]:
a=np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [10]:
a.ndim

1

In [4]:
a=np.array([(1,2,3),(4,5,6)])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.ndim

2

In [11]:
a.itemsize

4

In [12]:
a.dtype

dtype('int32')

In [13]:
a=np.array([1,2,3])

In [14]:
a.size

3

In [15]:
a=np.array([1,2,3,4,5,6,7])

In [16]:
a.size

7

In [17]:
a.shape

(7,)

In [18]:
a=np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])

In [20]:
a.shape

(2, 7)

In [27]:
a=np.array([(1,2,3,4),(5,6,7,8)])

In [28]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
a=a.reshape(4,2)

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
a=np.array([(1,2,3,4),(5,6,7,8)])

In [30]:
a[0,2]

3

In [31]:
a[0:,3]

array([4, 8])

In [32]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])

In [33]:
a[0:,3]

array([ 4,  6, 10])

In [34]:
a[0:2,3]

array([4, 6])

In [38]:
a=np.linspace(1,3,10)

In [39]:
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [40]:
a=np.array([1,2,3])

In [41]:
a.max()

3

In [42]:
a.min()

1

In [43]:
a.sum()

6

In [44]:
a=np.array([(1,2,3),(3,4,5)])

In [45]:
a.sum(axis=0)

array([4, 6, 8])

In [46]:
a.sum(axis=1)

array([ 6, 12])

In [47]:
a=np.array([(1,2,3),(3,4,5)])

In [48]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [49]:
np.std(a)

1.2909944487358056

In [50]:
a=np.array([(1,2,3),(3,4,5)])

In [51]:
b=np.array([(1,2,3),(3,4,5)])

In [52]:
a+b

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [53]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
a*b

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [55]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.vstack((a,b))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [58]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [59]:
a=np.array([(1,2,3),(3,4,5)])

In [60]:
a.ravel()

array([1, 2, 3, 3, 4, 5])

In [61]:
ar=np.array([1,2,3])

In [62]:
np.exp(ar)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [63]:
np.log(ar)

array([0.        , 0.69314718, 1.09861229])